# Configuration corrigée pour l'architecture hexagonale
api_controllers:
    resource:
        path: ../src/UI/Api/
        namespace: App\UI\Api
    type: attribute

# Route spéciale pour l'authentification JWT
api_login_check:
    path: /api/login_check

# Documentation API (sera ajoutée par nelmio/api-doc-bundle)
api_doc:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix: /api/doc
