# Configuration corrigée pour l'architecture hexagonale
api_controllers:
    resource:
        path: ../src/UI/Api/
        namespace: App\UI\Api
    type: attribute

# Route spéciale pour l'authentification JWT
api_login_check:
    path: /api/login_check

